import {
    blog,
    dashboard,
    dashboardActive,
    packages,
    payment,
    booking,
    calender,
    review,
    schedule,
} from '../../assets/images/dashboard'

export const sideBarLinkList = [
    {
        linkText: 'Dashboard',
        tooltipText: 'Dashboard',
        path: '/dashboard',
        icon: dashboard,
        activeIcon: '',
    },
    {
        linkText: 'Calendar',
        tooltipText: 'Calendar',
        path: 'calender',
        icon: calender,
        activeIcon: '',
    },
    {
        linkText: 'Pacakage',
        tooltipText: 'Package',
        path: 'package',
        icon: packages,
        activeIcon: '',
    },
    {
        linkText: 'Booking',
        tooltipText: 'Booking',
        path: 'booking',
        icon: booking,
        activeIcon: '',
    },
    {
        linkText: 'Schedule Tours',
        tooltipText: 'Schedule Tours',
        path: 'schedule',
        icon: schedule,
        activeIcon: '',
    },
    {
        linkText: 'Payment',
        tooltipText: 'Payment',
        path: 'payment',
        icon: payment,
        activeIcon: '',
    },
    {
        linkText: 'Blog',
        tooltipText: 'Blog',
        path: 'blog',
        icon: blog,
        activeIcon: '',
    },
    {
        linkText: 'Review',
        tooltipText: 'Review',
        path: 'review',
        icon: review,
        activeIcon: '',
    },
]
